# Generated by Django 4.1.3 on 2026-03-19 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiCollection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="集合名称")),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "source",
                    models.CharField(
                        default="POSTMAN", max_length=32, verbose_name="来源"
                    ),
                ),
                (
                    "raw_payload",
                    models.JSONField(blank=True, default=dict, verbose_name="原始内容"),
                ),
                (
                    "uploaded_file",
                    models.FileField(
                        blank=True, upload_to="api_collections/", verbose_name="上传文件"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="api_collections",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_collections",
                        to="projects.project",
                        verbose_name="所属项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "API 集合",
                "verbose_name_plural": "API 集合",
            },
        ),
        migrations.CreateModel(
            name="ApiEndpoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="接口名称")),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("GET", "GET"),
                            ("POST", "POST"),
                            ("PUT", "PUT"),
                            ("PATCH", "PATCH"),
                            ("DELETE", "DELETE"),
                        ],
                        default="GET",
                        max_length=10,
                        verbose_name="请求方法",
                    ),
                ),
                ("path", models.CharField(max_length=255, verbose_name="接口路径")),
                (
                    "headers",
                    models.JSONField(blank=True, default=dict, verbose_name="请求头"),
                ),
                (
                    "query_params",
                    models.JSONField(blank=True, default=dict, verbose_name="Query 参数"),
                ),
                (
                    "request_body",
                    models.JSONField(blank=True, default=dict, verbose_name="请求体"),
                ),
                (
                    "assertions",
                    models.JSONField(blank=True, default=list, verbose_name="断言"),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="endpoints",
                        to="api_testing.apicollection",
                        verbose_name="集合",
                    ),
                ),
            ],
            options={
                "verbose_name": "API 接口",
                "verbose_name_plural": "API 接口",
            },
        ),
    ]
