# Generated by Django 4.1.3 on 2026-03-20 08:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0001_initial"),
        ("api_testing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiTestRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "protocol",
                    models.CharField(
                        choices=[
                            ("HTTP", "HTTP/HTTPS"),
                            ("TCP", "TCP"),
                            ("WEBSOCKET", "WebSocket"),
                        ],
                        default="HTTP",
                        max_length=20,
                        verbose_name="协议",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="测试名称")),
                (
                    "method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("GET", "GET"),
                            ("POST", "POST"),
                            ("PUT", "PUT"),
                            ("PATCH", "PATCH"),
                            ("DELETE", "DELETE"),
                        ],
                        default="GET",
                        max_length=10,
                        verbose_name="请求方法",
                    ),
                ),
                ("target", models.CharField(max_length=255, verbose_name="目标地址")),
                (
                    "headers",
                    models.JSONField(blank=True, default=dict, verbose_name="请求头"),
                ),
                ("request_payload", models.TextField(blank=True, verbose_name="请求内容")),
                (
                    "response_status",
                    models.CharField(blank=True, max_length=64, verbose_name="响应状态"),
                ),
                (
                    "response_headers",
                    models.JSONField(blank=True, default=dict, verbose_name="响应头"),
                ),
                ("response_text", models.TextField(blank=True, verbose_name="响应文本")),
                ("response_hex", models.TextField(blank=True, verbose_name="十六进制响应")),
                (
                    "duration_ms",
                    models.PositiveIntegerField(default=0, verbose_name="耗时毫秒"),
                ),
                ("is_success", models.BooleanField(default=True, verbose_name="是否成功")),
                ("error_message", models.TextField(blank=True, verbose_name="错误信息")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="api_test_records",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="执行人",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_test_records",
                        to="projects.project",
                        verbose_name="所属项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "API 测试记录",
                "verbose_name_plural": "API 测试记录",
                "ordering": ["-created_at"],
            },
        ),
    ]
