# Generated by Django 4.1.3 on 2026-03-19 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestDataset",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="数据集名称")),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "schema",
                    models.JSONField(blank=True, default=list, verbose_name="字段定义"),
                ),
                ("tags", models.JSONField(blank=True, default=list, verbose_name="标签")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="datasets",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="datasets",
                        to="projects.project",
                        verbose_name="所属项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "测试数据集",
                "verbose_name_plural": "测试数据集",
            },
        ),
        migrations.CreateModel(
            name="TestDataRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "data",
                    models.JSONField(blank=True, default=dict, verbose_name="数据内容"),
                ),
                (
                    "remark",
                    models.CharField(blank=True, max_length=255, verbose_name="备注"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="datahub.testdataset",
                        verbose_name="数据集",
                    ),
                ),
            ],
            options={
                "verbose_name": "测试数据",
                "verbose_name_plural": "测试数据",
            },
        ),
    ]
