# Generated by Django 4.1.3 on 2026-03-19 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestSuite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="用例集名称")),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_suites",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建人",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="suites",
                        to="projects.project",
                        verbose_name="所属项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "用例集",
                "verbose_name_plural": "用例集",
            },
        ),
        migrations.CreateModel(
            name="TestCase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("case_id", models.CharField(max_length=64, verbose_name="用例 ID")),
                ("name", models.CharField(max_length=255, verbose_name="用例名称")),
                ("description", models.TextField(blank=True, verbose_name="用例描述")),
                ("expected_result", models.TextField(blank=True, verbose_name="预期结果")),
                ("precondition", models.TextField(blank=True, verbose_name="前置条件")),
                (
                    "execution_env",
                    models.CharField(blank=True, max_length=255, verbose_name="执行环境"),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("P0", "P0"),
                            ("P1", "P1"),
                            ("P2", "P2"),
                            ("P3", "P3"),
                        ],
                        default="P2",
                        max_length=10,
                        verbose_name="优先级",
                    ),
                ),
                (
                    "case_type",
                    models.CharField(
                        choices=[("AUTOMATED", "自动化用例"), ("MANUAL", "非自动化用例")],
                        default="MANUAL",
                        max_length=20,
                        verbose_name="用例类型",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("NATIVE", "平台内建"),
                            ("XMIND", "XMind"),
                            ("PDF", "PDF"),
                            ("EXCEL", "Excel"),
                            ("POSTMAN", "Postman JSON"),
                            ("PYTEST", "Pytest"),
                        ],
                        default="NATIVE",
                        max_length=20,
                        verbose_name="来源",
                    ),
                ),
                ("repo_url", models.URLField(blank=True, verbose_name="关联仓库")),
                (
                    "postman_collection",
                    models.JSONField(
                        blank=True, default=dict, verbose_name="Postman 集合"
                    ),
                ),
                (
                    "pytest_node",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Pytest 节点"
                    ),
                ),
                (
                    "steps",
                    models.JSONField(blank=True, default=list, verbose_name="步骤"),
                ),
                ("tags", models.JSONField(blank=True, default=list, verbose_name="标签")),
                ("is_active", models.BooleanField(default=True, verbose_name="有效")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="owned_cases",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="负责人",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="cases.testcase",
                        verbose_name="父节点",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cases",
                        to="projects.project",
                        verbose_name="所属项目",
                    ),
                ),
                (
                    "suite",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="cases",
                        to="cases.testsuite",
                        verbose_name="所属用例集",
                    ),
                ),
            ],
            options={
                "verbose_name": "测试用例",
                "verbose_name_plural": "测试用例",
                "ordering": ["project", "case_id"],
                "unique_together": {("project", "case_id")},
            },
        ),
        migrations.CreateModel(
            name="CaseAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128, verbose_name="文件标题")),
                (
                    "file",
                    models.FileField(upload_to="case_attachments/", verbose_name="附件"),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("NATIVE", "平台内建"),
                            ("XMIND", "XMind"),
                            ("PDF", "PDF"),
                            ("EXCEL", "Excel"),
                            ("POSTMAN", "Postman JSON"),
                            ("PYTEST", "Pytest"),
                        ],
                        default="NATIVE",
                        max_length=20,
                        verbose_name="来源类型",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="上传时间"),
                ),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="cases.testcase",
                        verbose_name="关联用例",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_case_attachments",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="上传人",
                    ),
                ),
            ],
            options={
                "verbose_name": "用例附件",
                "verbose_name_plural": "用例附件",
            },
        ),
    ]
