# Generated by Django 4.1.3 on 2026-03-19 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cases", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProjectDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128, verbose_name="文件标题")),
                (
                    "file",
                    models.FileField(
                        upload_to="project_case_documents/", verbose_name="文件"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("NATIVE", "平台内建"),
                            ("XMIND", "XMind"),
                            ("PDF", "PDF"),
                            ("EXCEL", "Excel"),
                            ("POSTMAN", "Postman JSON"),
                            ("PYTEST", "Pytest"),
                        ],
                        max_length=20,
                        verbose_name="文件类型",
                    ),
                ),
                (
                    "uploaded_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="上传时间"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="case_documents",
                        to="projects.project",
                        verbose_name="所属子项目",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_project_documents",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="上传人",
                    ),
                ),
            ],
            options={
                "verbose_name": "子项目文件",
                "verbose_name_plural": "子项目文件",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
