# Generated by Django 4.1.3 on 2026-03-19 08:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AsyncTaskExecution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "task_type",
                    models.CharField(
                        choices=[
                            ("SUITE_RUN", "用例集执行"),
                            ("ENV_DEPLOY", "环境部署"),
                            ("API_RUN", "API 执行"),
                        ],
                        default="SUITE_RUN",
                        max_length=32,
                        verbose_name="任务类型",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("PLATFORM", "平台任务"),
                            ("JENKINS", "Jenkins"),
                            ("GITLAB_CI", "GitLab CI"),
                        ],
                        default="PLATFORM",
                        max_length=32,
                        verbose_name="任务来源",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "待执行"),
                            ("RUNNING", "执行中"),
                            ("SUCCESS", "成功"),
                            ("FAILED", "失败"),
                            ("CALLBACK", "回调中"),
                        ],
                        default="PENDING",
                        max_length=16,
                        verbose_name="任务状态",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="任务标题")),
                ("description", models.TextField(blank=True, verbose_name="任务说明")),
                (
                    "external_job_name",
                    models.CharField(blank=True, max_length=128, verbose_name="外部任务名"),
                ),
                (
                    "external_build_id",
                    models.CharField(blank=True, max_length=128, verbose_name="外部构建号"),
                ),
                ("trigger_url", models.URLField(blank=True, verbose_name="触发地址")),
                (
                    "callback_token",
                    models.CharField(max_length=64, unique=True, verbose_name="回调令牌"),
                ),
                (
                    "payload",
                    models.JSONField(blank=True, default=dict, verbose_name="触发参数"),
                ),
                (
                    "result",
                    models.JSONField(blank=True, default=dict, verbose_name="执行结果"),
                ),
                (
                    "started_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="开始时间"),
                ),
                (
                    "finished_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="完成时间"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="task_executions",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="触发人",
                    ),
                ),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="task_executions",
                        to="projects.project",
                        verbose_name="所属项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "异步任务",
                "verbose_name_plural": "异步任务",
                "ordering": ["-created_at"],
            },
        ),
    ]
