# Generated by Django 4.1.3 on 2026-03-19 09:09

import async_tasks.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0001_initial"),
        ("async_tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="asynctaskexecution",
            name="callback_token",
            field=models.CharField(
                default=async_tasks.models.generate_callback_token,
                max_length=64,
                unique=True,
                verbose_name="回调令牌",
            ),
        ),
        migrations.CreateModel(
            name="CIIntegration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="集成名称")),
                (
                    "provider",
                    models.CharField(
                        choices=[("JENKINS", "Jenkins"), ("GITLAB_CI", "GitLab CI")],
                        default="JENKINS",
                        max_length=32,
                        verbose_name="CI 平台",
                    ),
                ),
                ("base_url", models.URLField(verbose_name="基础地址")),
                (
                    "trigger_path",
                    models.CharField(blank=True, max_length=255, verbose_name="触发路径"),
                ),
                (
                    "callback_base_url",
                    models.URLField(blank=True, verbose_name="平台回调前缀"),
                ),
                (
                    "jenkins_job_name",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="Jenkins Job"
                    ),
                ),
                (
                    "jenkins_token",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Jenkins Token"
                    ),
                ),
                (
                    "jenkins_username",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="Jenkins 用户名"
                    ),
                ),
                (
                    "jenkins_api_token",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Jenkins API Token"
                    ),
                ),
                (
                    "jenkins_crumb_url",
                    models.URLField(blank=True, verbose_name="Jenkins Crumb 地址"),
                ),
                (
                    "gitlab_project_id",
                    models.CharField(
                        blank=True, max_length=128, verbose_name="GitLab Project ID"
                    ),
                ),
                (
                    "gitlab_ref",
                    models.CharField(
                        blank=True,
                        default="main",
                        max_length=128,
                        verbose_name="Git 分支",
                    ),
                ),
                (
                    "gitlab_trigger_token",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="GitLab Trigger Token"
                    ),
                ),
                (
                    "gitlab_private_token",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="GitLab Private Token"
                    ),
                ),
                (
                    "default_payload",
                    models.JSONField(blank=True, default=dict, verbose_name="默认参数"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="启用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ci_integrations",
                        to="projects.project",
                        verbose_name="所属项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "CI 集成",
                "verbose_name_plural": "CI 集成",
                "ordering": ["project__name", "name"],
            },
        ),
        migrations.AddField(
            model_name="asynctaskexecution",
            name="integration",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="executions",
                to="async_tasks.ciintegration",
                verbose_name="CI 集成",
            ),
        ),
    ]
