# Generated by Django 4.1.3 on 2026-03-19 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("async_tasks", "0002_alter_asynctaskexecution_callback_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="asynctaskexecution",
            name="action_logs",
            field=models.JSONField(blank=True, default=list, verbose_name="动作日志"),
        ),
        migrations.AddField(
            model_name="asynctaskexecution",
            name="cancel_requested",
            field=models.BooleanField(default=False, verbose_name="请求暂停"),
        ),
        migrations.AddField(
            model_name="asynctaskexecution",
            name="celery_task_id",
            field=models.CharField(
                blank=True, max_length=128, verbose_name="Celery 任务 ID"
            ),
        ),
        migrations.AddField(
            model_name="asynctaskexecution",
            name="progress",
            field=models.PositiveIntegerField(default=0, verbose_name="执行进度"),
        ),
        migrations.AddField(
            model_name="asynctaskexecution",
            name="queue_name",
            field=models.CharField(
                default="platform", max_length=64, verbose_name="队列名称"
            ),
        ),
        migrations.AlterField(
            model_name="asynctaskexecution",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "待执行"),
                    ("QUEUED", "排队中"),
                    ("RUNNING", "执行中"),
                    ("PAUSED", "已暂停"),
                    ("SUCCESS", "成功"),
                    ("FAILED", "失败"),
                    ("CALLBACK", "回调中"),
                ],
                default="PENDING",
                max_length=16,
                verbose_name="任务状态",
            ),
        ),
    ]
