# Generated by Django 4.1.3 on 2026-03-19 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MockService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="服务名称")),
                (
                    "protocol",
                    models.CharField(
                        choices=[
                            ("HTTP", "HTTP"),
                            ("TCP", "TCP"),
                            ("UDP", "UDP"),
                            ("WEBSOCKET", "WebSocket"),
                        ],
                        default="HTTP",
                        max_length=16,
                        verbose_name="协议",
                    ),
                ),
                (
                    "host",
                    models.CharField(
                        default="0.0.0.0", max_length=64, verbose_name="监听地址"
                    ),
                ),
                ("port", models.PositiveIntegerField(default=8001, verbose_name="端口")),
                (
                    "route",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="HTTP 路由"
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True, verbose_name="启用")),
                (
                    "config",
                    models.JSONField(blank=True, default=dict, verbose_name="协议配置"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mock_services",
                        to="projects.project",
                        verbose_name="所属项目",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mock 服务",
                "verbose_name_plural": "Mock 服务",
            },
        ),
        migrations.CreateModel(
            name="MockRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=128, verbose_name="规则名称")),
                (
                    "matcher",
                    models.JSONField(blank=True, default=dict, verbose_name="匹配条件"),
                ),
                (
                    "response_status",
                    models.PositiveIntegerField(default=200, verbose_name="响应状态"),
                ),
                (
                    "response_headers",
                    models.JSONField(blank=True, default=dict, verbose_name="响应头"),
                ),
                (
                    "response_body",
                    models.JSONField(blank=True, default=dict, verbose_name="响应体"),
                ),
                (
                    "response_delay_ms",
                    models.PositiveIntegerField(default=0, verbose_name="延迟毫秒"),
                ),
                (
                    "sort_order",
                    models.PositiveIntegerField(default=0, verbose_name="顺序"),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rules",
                        to="mockserver.mockservice",
                        verbose_name="所属服务",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mock 规则",
                "verbose_name_plural": "Mock 规则",
                "ordering": ["sort_order", "id"],
            },
        ),
    ]
